<a href="https://colab.research.google.com/github/jmiguellsantos/Study-Data-Science/blob/main/Cria%C3%A7%C3%A3o_de_vetores_e_arrays_e_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
  

In [13]:
minha_lista = [1,2,3]

In [14]:
minha_lista1 = [4,5,6]


In [15]:
minha_lista2 = [7,8,9]

In [16]:
minha_lista

[1, 2, 3]

In [18]:
minha_lista1

[4, 5, 6]

In [19]:
minha_lista2

[7, 8, 9]

In [20]:
minha_matriz = [minha_lista, minha_lista1 , minha_lista2]

In [21]:
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
arr = np.zeros(3)

In [27]:
arr

array([0., 0., 0.])

In [28]:
arr = np.zeros((5, 5))

In [29]:
arr


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [33]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [34]:
np.random.rand(5)

array([0.13921339, 0.70700794, 0.48062311, 0.89745816, 0.72954084])

In [35]:
np.random.rand(5) * 100

array([14.46693888, 74.43291671, 58.60792181, 44.61761031, 69.5527402 ])

In [39]:
np.random.randn(5, 4, 3)

array([[[-1.60131598, -0.21395669,  0.05542526],
        [ 0.34696953,  0.9464118 ,  0.37949141],
        [ 0.10691199,  0.1093802 ,  1.2075669 ],
        [ 0.04299821,  0.03868086, -1.50920316]],

       [[ 0.67324819, -0.70267737,  0.03999327],
        [ 1.59260416, -0.78891091, -1.89666344],
        [ 2.28607551, -1.35732678, -0.88816574],
        [-1.20898091,  0.27076343,  1.38406102]],

       [[-0.04374748, -0.09127924, -0.99738477],
        [ 1.15445745,  0.81097421,  1.11708446],
        [-1.02955974, -1.25589721, -0.01320583],
        [ 0.39502443, -0.35079503, -2.9090985 ]],

       [[-0.25609594,  1.02445507,  0.93232659],
        [-0.97989014,  1.1232527 , -0.33697008],
        [-0.04404657,  1.04922511,  0.10460618],
        [-0.538125  , -0.36617817,  1.52635825]],

       [[ 1.83087477, -1.43912979,  0.03382399],
        [ 0.75831507, -1.12399859, -1.03600248],
        [-0.550179  ,  1.0237054 ,  0.13294632],
        [ 1.14049952, -0.96542249, -0.67017172]]])

In [40]:
np.random.randint(0, 100 ,10)

array([11,  6, 63,  4, 69, 82, 29,  3, 14, 48])

In [41]:
np.random.rand(5) * 100

array([26.30864959, 18.57940113, 45.37826556, 17.233097  , 19.04091422])

In [42]:
np.round(np.random.rand(5)*100,0)

array([64., 83.,  8., 59., 63.])

In [43]:
arr = np.random.rand(25)

In [44]:
arr

array([0.25279786, 0.37209056, 0.00461801, 0.55626451, 0.10573219,
       0.24743999, 0.59377223, 0.01726812, 0.88385176, 0.01932946,
       0.15094098, 0.80502669, 0.65534596, 0.56035611, 0.62935391,
       0.329677  , 0.06607493, 0.79969714, 0.04572615, 0.98631543,
       0.46067934, 0.75416004, 0.5887902 , 0.69520175, 0.69870816])

In [48]:
arr.reshape((5,5))

array([[0.25279786, 0.37209056, 0.00461801, 0.55626451, 0.10573219],
       [0.24743999, 0.59377223, 0.01726812, 0.88385176, 0.01932946],
       [0.15094098, 0.80502669, 0.65534596, 0.56035611, 0.62935391],
       [0.329677  , 0.06607493, 0.79969714, 0.04572615, 0.98631543],
       [0.46067934, 0.75416004, 0.5887902 , 0.69520175, 0.69870816]])

In [49]:
arr

array([0.25279786, 0.37209056, 0.00461801, 0.55626451, 0.10573219,
       0.24743999, 0.59377223, 0.01726812, 0.88385176, 0.01932946,
       0.15094098, 0.80502669, 0.65534596, 0.56035611, 0.62935391,
       0.329677  , 0.06607493, 0.79969714, 0.04572615, 0.98631543,
       0.46067934, 0.75416004, 0.5887902 , 0.69520175, 0.69870816])

In [50]:
arr.shape

(25,)

In [52]:
arr.max() #maior valor

0.9863154267196534

In [54]:
arr.min()#menor valor

0.004618008648379024

In [56]:
arr.argmax()#o indice em que o maior valor se encontra


19

In [58]:
arr.argmin()#o indicie que o menor valor se encontra

2